### ISSUE TITLE
panic: frame length (86400) less than expected (115200)

### ISSUE THREAD

**Issue by Sean-Der** [dialupdotcom/ascii_roulette#19]
This is on my Mac

Version 10.13.6
Macbook Pro (13-inch, 2017)

**Comment by maxhawkins** [comment]
Thanks for reporting. Do you know what triggered it?

**Comment by Sean-Der** [comment]
This is right on startup! This also always had the visual corruption.

I don't know the AVFoundation APIs, is it possible that you aren't getting back the pix_fmt you expect?

**Comment by maxhawkins** [comment]
The camera doesn't activate until the intro animation is done. Could it be the ivf reader for the intro?

**Comment by Sean-Der** [comment]
Sorry right on startup for the camera, the videos do play correctly!

**Comment by maxhawkins** [comment]
Good to know!

I bet the camera doesn't support the dimensions we request and is sending different ones. I'll look into this...

**Comment by Sean-Der** [comment]
Oh good idea.

If you have any debugging code I can run send it my way and can test it out!

**Comment by maxhawkins** [comment]
It appears #25 and this issue are related.

When I launched Photo Booth I got this error

**Comment by maxhawkins** [comment]
1. This should return an error rather than panicking
2. Maybe this has to do with the image dimensions changing to an unexpected size

**Comment by maxhawkins** [comment]
Possible solution to 1)

Pass the frame size in the cam_avfoundation callback. If it's different than expected the code will scale it anyway.

**Comment by maxhawkins** [comment]
This may be fixed by 27609cf3f98fcefe2b107664aa0a793ae1356361
